### ISSUE TITLE
IDL parser bug: <enum> redefined

### ISSUE THREAD

**Issue by fissive** [PrismTech/opensplice#13]
`idlpp -l cs` accepts this:

```
enum First { A };
enum Second { A };
```

And this:

```
enum First { A, B };
enum Second { A };
```

But this:

```
enum First { A }; // or enum First { A, anything... }
enum Second { A, B };
```

Produces the following error:
`1>  ***DDS parse error Second redefined at line: 2`

This becomes quickly apparent when you have a guard value:

```
enum XStatus { UNKNOWN, X1, X2, ... };
enum YStatus { UNKNOWN, Y1, Y2, ... };
```

So I'm a bit surprised nobody has encountered it before and have to wonder if I haven't done something stupid, but the same IDL processes fine under RTI Connext.

**Comment by michielb-prismtech** [comment]
with the 6.7 release following idl input:
```
module enumTest {
    enum First { A };
    enum Second { A, B };

    struct Type {
        First f;
        Second s;
    };
#pragma keylist Type f
};
```
does not produce an error while it did with the 6.4 release.
