### ISSUE TITLE
Building OpenSplice from source

### ISSUE THREAD

**Issue by ainchauspe** [PrismTech/opensplice#22]
Hi,

This is Anita from Erle Robotics. I'm trying to install OpenSplice to be able to work with ROS 2 but I'm having troubles. For this purpose I've made an ARM chroot and I have taken the following steps: 

1- I've gone to http://www.prismtech.com/dds-community/software-downloads and download the .tar file needed (I've downloaded the second one). I've followed the instructions described in  http://www.prismtech.com/dds-community/software-downloads/installing 

1.2- Unzip `tar -xzf OpenSpliceDDSV6.4.140407OSS-HDE-armv7l.linux-release-installer.tar.gz` . This will create the HDE folder.
    1.3- Replace all the @@INSTALLDIR@@ with the absolute path of the working directory: `sed -i "s|@@INSTALLDIR@@|$PWD|g" HDE/armv7l.linux/release.com`
    1.4- Checkout: `echo $PWD` y `cat HDE/x86.linux2.6/release.com`
    1.5- Source $PWD/HDE/armv7l.linux/release.com

2- On the other hand, I've followed the steps from the following website  http://www.prismtech.com/dds-community/building

2.1- Install just the necessary packages:  gcc, gmake, gawk, flex, bison and perl. 
2.2- Go to  `HDE/armv7l.linux/src` and extract the `tar -xzf OpenSpliceDDS-src.tar.gz`
    2.3- Go to  `OpenSpliceDDS` and execute `source ./configure`
    2.4- If everything is OK, execute `make -j4 && make install`

The error I get is described on: https://gist.github.com/ainchauspe/9abb274edec737d505d6

**Comment by kortstee** [comment]
For 1) What's not working for you?
For 2.4) The makefiles do not support parallel building, so if you refrain from using the "-j" your error goes away I believe.
