### ISSUE TITLE
Bug in serializing messages with sequences of 64 bit values

### ISSUE THREAD

**Issue by dirk-thomas** [PrismTech/opensplice#25]
For very specific messages OpenSplice seems to serialize the message incorrectly. Let me describe a pretty specific message which leads to it:

```
long prefix;
sequence<boolean> bool_values;
sequence<long long> int64_values;
long check
```

I left both sequences empty and set `check` to a known value not equal to zero. I think it is essential that one of the sequences is 64 bit and a second sequence is in the message. The resulting serialized message was 4 bytes longer then specified in CDR. Therefore no subscriber received the `check` value correctly. The prefix field might or might not be necessary - it might depend on the alignment of the message.

Since previous tickets in this repo haven't received much attention I didn't spend more time on a simple reproducible example yet. Please let me know if you need further information.

**Comment by michielb-prismtech** [comment]
This issue is fixed in the 6.7 release
