### ISSUE TITLE
configure hangs with GSOAP V2.8 and open splice 6.7

### ISSUE THREAD

**Issue by matthewpang** [PrismTech/opensplice#32]
With the [configure script](https://github.com/PrismTech/opensplice/blob/master/bin/checkconf) LINE 561 and GSOAP 2.8 (tested on 2.8.46 and 2.8.47) on debian stretch running on aarch64 

1) calling soapcpp2 -help no longer seems to return the version correctly. 
2) This results in the script calling soapcpp2 -v which does not exit and hangs 

FIX : 
A better way to do this is : GSOAP_VERSION=\`soapcpp2 -V`

Implemented on my branch here:
https://github.com/matthewpang/opensplice/commit/e1f6e8e6539e87dcfae8eef520bd6519da8a3784

**Comment by michielb-prismtech** [comment]
agreed, fix pushed
